### ISSUE TITLE
A question regarding CH table engine choice

### ISSUE THREAD

**Issue by adhasahar97** [Altinity/clickhouse-sink-connector#149]
I've been tinkering with the project to support ReplicatedReplacingMergeTree and been testing it on EKS. So far it's working fine expect 1 thing. Deletion. After reading a documentation here [CollapsingMergeTree vs ReplacingMergeTree](https://kb.altinity.com/engines/mergetree-table-engine-family/collapsing-vs-replacing/), I just realised ReplacingMergeTree doesn't support deletion. So I want to know what is the purpose of SIGN column in the table when it doesn't delete the row with -1 value. Why don't we use VersionedCollapsingMergeTree engine instead?

**Comment by aadant** [comment]
This project, similar to MaterializedMySQL, currently only supports Replacing*MergeTree engine.  If you want to hide the deleted values, you can add a row policy. We expect improvements to the engine (work in progress) to automatically discard the deleted rows at merge time and final time.
