### ISSUE TITLE
mysql version: 5.7.99-log not pass

### ISSUE THREAD

**Issue by poseidon2011** [Altinity/clickhouse-sink-connector#187]
mysql version: 5.7.99-log   debezium-connector-setup-schema-registry.sh   "error_code":400,"message":"Connector configuration is invalid and contains the following 1 error(s):\nUnable to connect: Unknown system variable 'transaction_isolation'

mysql version:  5.7.19-log  pass

**Comment by aadant** [comment]
It is related to the Java MySQL driver not being compatible with 5.7.

We tested with MySQL 8. There should be a workaround though.

**Comment by aadant** [comment]
https://stackoverflow.com/questions/51016980/java-sql-sqlexception-unknown-system-variable-tx-isolation

**Comment by aadant** [comment]
@poseidon2011 I would recommend to upgrade to MySQL 8 if possible. It has been out for a while.

this is a new project, so we develop on the modern releases, CH and MySQL.

otherwise, it may be possible to use an earlier version of the connector but there are lot lf benefits to upgrade to MySQL 8.

**Comment by aadant** [comment]
MySQL 5.7 is EOL soon, closing.
