### ISSUE TITLE
Alter table add/drop column

### ISSUE THREAD

**Issue by tuanuet** [Altinity/clickhouse-sink-connector#190]
Hi, thank you for the project. When I alter mysql (add, drop column), clickhouse doesn't run alter!

**Comment by aadant** [comment]
This is a current limitation of the project. You need to run the alter on both sides for now.
@subkanthi is working on a fix.

**Comment by subkanthi** [comment]
@tuanuet , we now support DDL in the lightweight version,
Here is the list of currently supported ALTER statements
https://github.com/Altinity/clickhouse-sink-connector/blob/develop/sink-connector-lightweight/README.md
