### ISSUE TITLE
"auto.create.tables": true setting doesn't work correct (altinity/clickhouse-sink-connector:2022-07-26)

### ISSUE THREAD

**Issue by AlmostIvanSidorov** [Altinity/clickhouse-sink-connector#22]
Looks like auto creation with the first "INSERT" in one step doesn't work correct (but creation of table in ClickHouse works correct if we don't drop table after first insert which is always wrong, all other inserts work correct). I tried with different variants of sink start up.

**Sink ver.:**
 altinity/clickhouse-sink-connector:2022-07-26 

Some retries and results:
**Case 1:**
    1) restart sink/non restart sink 
    2) sysbench test "load insert" + "auto.create.tables": true in sink
    3) optimize CH table
    3) **drop** table in the end
**result:** data in MySQL and CH always different.

**Case 2**:
    1) restart sink/non restart sink 
    2) sysbench test "load insert" + "auto.create.tables": true in sink
    3) optimize CH table
    3) **truncate** table in the end
**result:** data in MySQL and CH on the first run different then always same.

**Comment by subkanthi** [comment]
Thanks @AlmostIvanSidorov.
