### ISSUE TITLE
With lightweight version pg_wal is taking a lot of disk space

### ISSUE THREAD

**Issue by sudmed** [Altinity/clickhouse-sink-connector#246]
Hello, I have postgres, clickhouse and sinc-connector lightweight version. 
When sink-connector-lightweight starts working, thousands of 16 MB files accumulate in the directory `/var/lib/pgsql/14/data/pg_wall` and this value grows. Even the restriction in `postgresql.conf` by the `wal_keep_segments` parameter does not work.
Replication slot "debezium" is active, the replication works. Could you tell me why `pg_wal` is not being cleared?

**Comment by subkanthi** [comment]
Hi @sudmed ,
looks like a problem similar to this
https://stackoverflow.com/questions/65409273/debezium-causes-postgres-to-run-out-of-disk-space-on-rds

Can you try adding `heartbeat.interval.ms` to the environment variables, Sink connector just passes the variables to Debezium.

**Comment by subkanthi** [comment]
closing this, heartbeat is the suggested option for this.
#630
