### ISSUE TITLE
Schema from different CH database

### ISSUE THREAD

**Issue by faridco** [Altinity/clickhouse-sink-connector#259]
I have a table that replicates well. But when I create table with the same name in different database in CH I'm getting an error
```
6363 2023-06-07 11:04:46.582 [pool-1-thread-3] ERROR com.altinity.clickhouse.sink.connector.db.DbWriter  - ******* ERROR inserting Batch *****************
java.sql.BatchUpdateException: Code: 16. DB::Exception: No such column test_generated_column in table test_cdc.ingesting (cff45383-6e6b-4824-b554-da931053c8bf). (NO_SUCH_COLUMN_IN_TABLE) (version 23.4.2.11 (official build))
, server ClickHouseNode [uri=http://172.0.0.120:8123/test_cdc, options={custom_settings=allow_experimental_object_type=1,client_name=Agent_1}]@-266091542
```

where `test_generated_column` is the column in the `ingesting` table, but in different database (not `test_cdc`) inside the same cluster.

while lightweight connector is running I can create table/view with the same `ingesting` name in different database, but right after restart of the connector I'm getting errors like above.

**Comment by subkanthi** [comment]
Hi @faridco , we are working on a fix, we should have the new version released in a day or two, will update here.

**Comment by faridco** [comment]
@subkanthi any updates on this?

**Comment by subkanthi** [comment]
> @subkanthi any updates on this?

@faridco testing the fix, will update you here tomorrow , thanks

**Comment by subkanthi** [comment]
Hi @faridco , #265 fixes the bug.
If you are using docker.
you can use this tag.
`export SINK_LIGHTWEIGHT_VERSION=2023-06-17`

`clickhouse_debezium_embedded:2023-06-17`

**Comment by faridco** [comment]
@subkanthi thank you
