### ISSUE TITLE
Timed out waiting to flush EmbeddedEngine offsets to storage 

### ISSUE THREAD

**Issue by congvmit** [Altinity/clickhouse-sink-connector#287]
Currently I am facing the issue: "Timed out waiting to flush EmbeddedEngine offsets to storage" while syncing a table more than 1M records.

ERROR io.debezium.embedded.EmbeddedEngine  - Timed out waiting to flush EmbeddedEngine{id=company} offsets to storage
This is my config:
``` yaml
offset.flush.interval.ms: 10000
offset.flush.timeout.ms: 60000
```

Can you please help me? What should I do now?

**Comment by subkanthi** [comment]
Hi @congvmit ,
Can you please provide more information, does it only happen with 1M records.
Also are you replicating from MySQL or PostgreSQL?

Im assuming you updated the clickhouse username/password fields in the config.
```
offset.storage.jdbc.url: "jdbc:clickhouse://clickhouse:8123/altinity_sink_connector"
offset.storage.jdbc.user: "root"
offset.storage.jdbc.password: "root"

schema.history.internal.jdbc.url: "jdbc:clickhouse://clickhouse:8123/altinity_sink_connector"
schema.history.internal.jdbc.user: "root"
schema.history.internal.jdbc.password: "root"
```
