### ISSUE TITLE
Ability to pass JAVA_OPTS to the sink connector 

### ISSUE THREAD

**Issue by aadant** [Altinity/clickhouse-sink-connector#325]
Tried

```
  environment:
            - "JAVA_OPTS=-Xmx64G  -Xms64G"
```

```
root@13498bb41e0d:/# ps aux | grep java
root          1  658  0.3 49479196 6996512 ?    Ssl  20:20   1:51 java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app.jar /config.yml com.altinity.clickhouse.debezium.embedded.ClickHouseDebeziumEmbeddedApplication
```

**Comment by AdamKatzDev** [comment]
@aadant I've tried to run the latest docker image but looks like it still does not respect JAVA_OPTS, there is still no way to increase memory but to overwrite docker entrypoint.

I've taken a look at [the fix](https://github.com/Altinity/clickhouse-sink-connector/pull/329) and pretty sure it does not fix the described issue.

**Comment by aadant** [comment]
@AdamKatzDev the fix is to edit the config to pass the memory parameters

**Comment by minguyen9988** [comment]
> @aadant I've tried to run the latest docker image but looks like it still does not respect JAVA_OPTS, there is still no way to increase memory but to overwrite docker entrypoint.
> 
> I've taken a look at [the fix](https://github.com/Altinity/clickhouse-sink-connector/pull/329) and pretty sure it does not fix the described issue.

this is one way to pass the java opts directly to the program, in pure docker you can use

```docker run --entrypoint "abc" xxx ```

**Comment by AdamKatzDev** [comment]
@aadant you can try to repeat your case and try to pass `JAVA_OPTS` using `environment`, you won't see a difference.
Also somehow the latest image at the moment I've tried to test this feature was 6 days old, i.e. older than the date the fix was merged.

@minguyen9988 in your PR you've tried to add `JAVA_OPTS` in `ENTRYPOINT` of the Dockerfile  but then this code is reverted in the next commit. Was there any problem with the approach?

**Comment by minguyen9988** [comment]
see the latest commit on that file on develop branch, I ditch the env var and just input the values in it

https://github.com/Altinity/clickhouse-sink-connector/blob/develop/sink-connector-lightweight/docker/docker-compose.yml#L116
