### ISSUE TITLE
Support partitions when migrating to CH

### ISSUE THREAD

**Issue by aadant** [Altinity/clickhouse-sink-connector#332]
The DDL parser should detect MySQL partitions and migrate them to CH.

MySQL : 

```
create table t(
id int primary key,
dt date not null
) engine=InnoDB
PARTITION BY RANGE  COLUMNS(dt)
(PARTITION p20201231 VALUES LESS THAN ('2021-01-01') ENGINE = InnoDB,
 PARTITION p20211230 VALUES LESS THAN ('2021-12-31') ENGINE = InnoDB,
 PARTITION p20211231 VALUES LESS THAN ('2022-01-03') ENGINE = InnoDB,
 PARTITION p20220103 VALUES LESS THAN ('2022-01-04') ENGINE = InnoDB,
 PARTITION p20220104 VALUES LESS THAN ('2022-01-05') ENGINE = InnoDB,
 PARTITION p20220105 VALUES LESS THAN ('2022-01-06') ENGINE = InnoDB
);
```

CH :

```
CREATE TABLE t (id int NULL,
dt Date32 not null,
`_version` UInt64 DEFAULT 0,
`is_deleted` UInt8 DEFAULT 0
) engine=ReplacingMergeTree(_version,is_deleted)  partition by dt order by id
```

Please note that `clickhouse_loader.py` already supports this for the initial migration.

**Comment by aadant** [comment]
It should be possible to override the partitioning key (see https://github.com/Altinity/clickhouse-sink-connector/issues/323)

**Comment by aadant** [comment]
This is already implemented in `clickhouse_loader.py`
./sink-connector/python/db_load/clickhouse_loader.py

**Comment by subkanthi** [comment]
Current sink connector parsing logic:

```
CREATE TABLE t(id Nullable(Int32),dt Date32 NOT NULL ,
`_version` UInt64,`is_deleted` UInt8) Engine=
ReplacingMergeTree(_version,is_deleted) PARTITION BY  (dt) ORDER BY tuple()
```

**Comment by subkanthi** [comment]
Parsing of primary key columns added.
Fixed in #379

**Comment by Selfeer** [comment]
The issue was manually verified by the Altinity QA team and marked as `qa-verified`.

Build used for testing: `altinityinfra/clickhouse-sink-connector:443-678d8ae2567c2c1d89f5430fa57ede619d6ea851-lt`

We've verified that when creating a partitioned table in ClickHouse it is correctly mapped to the partitioned table in source MySQL table. Partitions are correctly created in ClickHouse based on the specified partition key.

Issue raised during testing is a separate scenario, which is not related to this one. 

Link to the issue: https://github.com/Altinity/clickhouse-sink-connector/issues/461

**Comment by aadant** [comment]
When mysqldump dumps tables, it added a comment and this case is not yet supported : 
```
create table t(
id int not null,
dt date not null,
primary key(id, dt)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8
/*!50500 PARTITION BY RANGE  COLUMNS(dt)
(PARTITION p20201231 VALUES LESS THAN ('2021-01-01') ENGINE = InnoDB,
 PARTITION p20211230 VALUES LESS THAN ('2021-12-31') ENGINE = InnoDB,
 PARTITION p20211231 VALUES LESS THAN ('2022-01-03') ENGINE = InnoDB,
 PARTITION p20220103 VALUES LESS THAN ('2022-01-04') ENGINE = InnoDB,
 PARTITION p20220104 VALUES LESS THAN ('2022-01-05') ENGINE = InnoDB,
 PARTITION p20220105 VALUES LESS THAN ('2022-01-06') ENGINE = InnoDB
)*/;
```

see also https://github.com/Altinity/clickhouse-sink-connector/issues/1186
