### ISSUE TITLE
The Iterator in `DbWriter.groupQueryWithRecords()` throws `NoSuchElementException`

### ISSUE THREAD

**Issue by IlyaTsoi** [Altinity/clickhouse-sink-connector#350]
I think this occurs when multiple ClickhouseBatchExecutor threads are processing a shared queue in parallel. But i have seen this error in logs even with single thread. The issue is here:
```java
        Iterator iterator = records.iterator();
        while (iterator.hasNext()) {
            ClickHouseStruct record = (ClickHouseStruct) iterator.next();
```
`Iterator.next()` tries to get already removed elements. As a workaround i have solved this issue by replacing `Iterator` by `poll()` method of `ConcurrentLinkedQueue` class:
```java
        while (!records.isEmpty()) {
            ClickHouseStruct record = (ClickHouseStruct) records.poll();
```
So this part of the code at the end of method is unnecessary:
```java
            if(result) {
                iterator.remove();
            }
```
Also, I think it would be better to limit the number of records that can be processed by a single thread from single topic. It might be a number of processed records:
```java
        int processedRecords = 0;
        while (!records.isEmpty() && processedRecords < batchLimit) {
            ClickHouseStruct record = (ClickHouseStruct) records.poll();
            processedRecords += 1;
```
Or timeout:
```java
        long startTime = System.currentTimeMillis();
        while (!records.isEmpty() && System.currentTimeMillis() - startTime < timeout) {
            ClickHouseStruct record = (ClickHouseStruct) records.poll();
```

**Comment by subkanthi** [comment]
In 2.0.0, the logic was changed to `poll`.
