### ISSUE TITLE
Add logic to ignore MATERIALZED or ALIAS columns in insert statements.

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#357]
If the table schema contains `MATERIALIZED` or `ALIAS` columns , they should be ignored.

```
    `_version` UInt64 MATERIALIZED 1,
    `_deleted` UInt8 MATERIALIZED 0,
    `_updated` DateTime MATERIALIZED now()
```

**Comment by tellienne** [comment]
Hi!
any news about this?

**Comment by tellienne** [comment]
Hello!
is there any news on this issue? We encountered it in our data transfer :(

**Comment by subkanthi** [comment]
> Hello! is there any news on this issue? We encountered it in our data transfer :(

Hi @tellienne , working on it, will have a fix early next week.

**Comment by amnaak** [comment]
@subkanthi Any update on this?
waiting for a fix to exclude the Materialized columns using `column.exclude.list:`
