### ISSUE TITLE
Alter table add/drop column PostgreSql

### ISSUE THREAD

**Issue by tellienne** [Altinity/clickhouse-sink-connector#417]
Hi! 
We are trying to use sink-connector-lightweight to replicate data from PostgreSQL to Clickhpuse. Does it support ddl with postgresql (add, drop column)?
We made an alter in the postgres table (ALTER TABLE table_name ADD COLUMN) but in the clickhouse the table did not change

**Comment by subkanthi** [comment]
Hi @tellienne ,
Currently, the sink-connector lightweight version does not support replication of DDL's in PostgreSQL.
This comes from the limitations in logical decoding feature 
https://debezium.io/documentation/reference/stable/connectors/postgresql.html

```
Logical decoding does not support DDL changes. This means that the connector is unable to report DDL change events back to consumers.

```

**Comment by tellienne** [comment]
Well, we will make alters manually in clickhouse :)
Thank you!
