### ISSUE TITLE
renaming tables when copying from postgres

### ISSUE THREAD

**Issue by tellienne** [Altinity/clickhouse-sink-connector#435]
Hi!
We use the connector to copy data from postgresql to clickhouse. We have a problem related to naming tables in PostgreSQL.
The table name in the PostgreSQL database contains '-', for example, 'test-table-master'. We enabled auto-creation of tables and now the connector tries to create a table with the same name in the clickhouse. As a result, we get a syntax error in clickhose.
Is it possible to replace '-' with '_'  when auto-creation of tables in clickhouse is enabled? For example, rename 'test-table-master' on 'test_table_master'.
Or maybe you know another solution? :(

**Comment by subkanthi** [comment]
Hi @tellienne ,
We currently dont have the feature of providing table name overrides.
we will  have this implemented soon.

cc: @aadant

**Comment by subkanthi** [comment]
will add a quick fix to replace '-' with '_' for now.

**Comment by aadant** [comment]
@subkanthi - should work in clickhouse if the table names are escaped ! Maybe it is an old issue.

**Comment by tellienne** [comment]
We use docker-image altinityinfra/clickhouse-sink-connector:405-fe4aa9de369b639a59f579a81d0fdd5d3ac32f97-lt.

connector logs:
`Caused by: java.io.IOException: Code: 62. DB::Exception: Syntax error: failed at position 19 ('-'): -history_2023_05(`supplier_guid` String NOT NULL,`supplier_id` UUID NOT NULL,`supplier_store_id` String NOT NULL,`day_updated_at` DateTime64(6) NOT NULL,`base_u. Expected one of: token, Dot, UUID, ON, OpeningRoundBracket, storage definition, ENGINE, PARTITION BY, PRIMARY KEY, ORDER BY, SAMPLE BY, TTL, EMPTY AS, AS, COMMENT, INTO OUTFILE, FORMAT, SETTINGS, end of query. (SYNTAX_ERROR) (version 23.10.5.20 (official build))`

the table is called  price-history_2023_05.

We copy all tables from the public schema without specifying 'table.include.list'

**Comment by aadant** [comment]
@subkanthi I believe this was fixed by this bug fix https://github.com/Altinity/clickhouse-sink-connector/issues/413

**Comment by subkanthi** [comment]
@tellienne the fix was added , please try this docker tag `altinityinfra/clickhouse-sink-connector:439-dfd65c5fddb2ddac0380ecc116a87ccc20ec7aa9-lt`
