### ISSUE TITLE
new table in Postgresql

### ISSUE THREAD

**Issue by tellienne** [Altinity/clickhouse-sink-connector#438]
Hello!
Need some help with another case.
We copy all the tables in the public schema to clickhouse from Postgres. When a new table is added to Postgres, it will appear in the clickhouse only after the connector is restarted and the data already existing in the table in Postgres is updated again.
As a result, we lose some of the data in the new table.
Is there any way for the connector to take a snapshot of new tables and after that replicate them to the clickhouse?

Playback:
1. creating a table in Postgres
2. Filling it with data
The table does not appear in clickhouse.
3. connector restart
Still no table in clickhouse
4. update or insert new data into the postgres table
5. The table appears in the clickhouse, but it only contains data that was changed by the update/insert

thanks :)

**Comment by subkanthi** [comment]
@tellienne marking this as completed.
https://github.com/Altinity/clickhouse-sink-connector/blob/develop/doc/incremental_snapshot.md
