### ISSUE TITLE
Unclear docker images and releases strategy for lightweight version

### ISSUE THREAD

**Issue by emmanuelm41** [Altinity/clickhouse-sink-connector#446]
Hello there! I came across this repository searching on internet with google, and it looks pretty amazing! I have been playing with the testing docker compose files to experience the possibilities the sink connector brings. However, it is unclear to me if there is any official docker image release process. I found the Altinity and AltinityInfra orgs on dockerhub. Neither of them seems to releases organized by some kind of versioning, like semver. Could you please clarify my if some docker image for new releases exists, and point me to it? Moreover, I am not sure which one is the latest release, as tags go from v0.0.5 to v5.0.0 in different dates. Is it possible to clarify that too?

**Comment by subkanthi** [comment]
Hi @emmanuelm41 , we have been following a consistent release strategy for the last couple of releases , `2.0.0` and `2.0.1`. Docker images were published in `Altinity` repos in dockerhub.
