### ISSUE TITLE
Feature request: Support for Avro messages.

### ISSUE THREAD

**Issue by UnamedRus** [Altinity/clickhouse-sink-connector#5]
Debezium have support to produce messages in avro format, which allow better compression compared to JSON.
https://debezium.io/documentation/reference/stable/configuration/avro.html

**Comment by subkanthi** [comment]
> Debezium have support to produce messages in avro format, which allow better compression compared to JSON.
> https://debezium.io/documentation/reference/stable/configuration/avro.html

Avro is supported and tested with apicurio schema registry
