### ISSUE TITLE
replacingmergetree.delete.column property doesn't work for postgres

### ISSUE THREAD

**Issue by DenisFilippovArammeem** [Altinity/clickhouse-sink-connector#501]
When synchronizing data between postgres and clickhouse using clickhouse-sink-connector, I'm trying to use
`replacingmergetree.delete.column: "_sign"`
property to auto-create ReplacingMergeTree table with _sign column as deletion indicator.
But sink-connector creates the table like the following:
```
CREATE TABLE my_database.test
(
    `id` Int32,
    `name` Nullable(String),
    `_sign` Int8,
    `_version` UInt64
)
ENGINE = ReplacingMergeTree(_version)
```
How can I specify that I need `ReplacingMergeTree(_version, _sign) ` in the table declaration

**Comment by subkanthi** [comment]
With `2.0.2` release, in the kafka version, the `is_deleted` column will be created for `ReplacingMergeTree`, however its not customizable.

**Comment by DenisFilippovArammeem** [comment]
thanks, @subkanthi 
Is there any chance to make it customizable?
