### ISSUE TITLE
Remove references to clickhouse.server.database

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#602]
With `2.1.0` and support of multiple databases, the `clickhouse.server.database` configuration parameter is not used, references need to   be removed.

**Comment by thewandererbg** [comment]
Hi, with 2.1.0, in case of multiple databases, is there any way to map the source databases into a list of predefined clickhouse databases such as:
db1 -> ch_db1
db2 -> ch_db2
Thank you

**Comment by subkanthi** [comment]
Hi @thewandererbg , currently no, but we can work on this feature for the next release

**Comment by strafer** [comment]
@subkanthi is there a way to write to a database with a name other than the name of the source database in version 2.1.0?

**Comment by subkanthi** [comment]
> @subkanthi is there a way to write to a database with a name other than the name of the source database in version 2.1.0?

Hi @strafer , we will be adding support for this in the next release `2.2.0`
https://github.com/Altinity/clickhouse-sink-connector/issues/622
