### ISSUE TITLE
Simplify the process of adding more tables to replicate.

### ISSUE THREAD

**Issue by aadant** [Altinity/clickhouse-sink-connector#606]
**How to reproduce :**

in `config.yml`

```
database.include.list: "mydb"
table.include.list: "mydb.mytable"
snapshot.mode: "schema_only"
```

- start the sink-connector (docker-compose up)

- check that replication is working fine (no error in the log) and is not lagging
```
select * from altinity_sink_connector.show_replica_status\G
```
- add another table to replication in in `config.yml`
```
database.include.list: "mydb"
table.include.list: "mydb.mytable,mydb.mytable2"
```

- restart the sink-connector (docker-compose up)

- debezium will throw an error 

**Workaround :**

- stop the sink-connector

- in `config.yml`

```
snapshot.mode: "schema_only_recovery"
```

-  purge the schema history 
``` 
truncate altinity_sink_connector.replicate_schema_history
```

- restart the sink-connector (docker-compose up)

once replication works fine, you can come back to 

```
snapshot.mode: "schema_only_recovery"
```

not very usable to change the replication filters, it should work out of the box.

**Comment by subkanthi** [comment]
https://debezium.io/documentation/reference/stable/configuration/signalling.html#debezium-signaling-ad-hoc-incremental-snapshots

Debezium Signals were added to support this functionality of adding tables.

**Comment by subkanthi** [comment]
https://stackoverflow.com/questions/66221430/how-to-add-new-table-to-debezium-mysql-connector

```
Since debezium:1.6 you should be able to send a signal to snapshot the newly added table. https://debezium.io/documentation/reference/1.7/configuration/signalling.html https://debezium.io/blog/2021/05/06/debezium-1-6-alpha1-released/

Sending a signal is done via inserting a record in a specific table:

INSERT INTO myschema.debezium_signal VALUES('ad-hoc-1', 'execute-snapshot', '{"data-collections": ["schema1.table1", "schema1.table2"]}')
And to make this feature available you should first create this table

CREATE TABLE debezium_signal (id VARCHAR(42) PRIMARY KEY, type VARCHAR(32) NOT NULL, data VARCHAR(2048) NULL);
* syntax may differ between database types

Also the signal table must be added among the captured data collections, i.e., included in the table.include.list parameter.
```

**Comment by subkanthi** [comment]
**Proposal**
```
./sink-connector-client add-tables <table_name_1, table_name_2>
```

This will send a REST API signal to send a incremental snapshot signal to debezium to start snapshotting of the new table.
This will be a asynchronous call and so `sink-connector-client` will return immediately.

**Comment by subkanthi** [comment]
The sink connector should also persist the configuration changes to the `config.yml`. Need to document the approach of making changes in configuration and restarting the configuration.

**Comment by subkanthi** [comment]
On `2.3.0` , this process currently fails because of the bug in debezium 2.7

clickhouse-sink-connector-lt_1  | 2024-09-04 19:51:56.910 ERROR - Error stating connector: CauseUnable to find schema_only_recovery snapshotter. Please check your configuration.

https://issues.redhat.com/browse/DBZ-8147?jql=text%20~%20%22unable%20to%20find%20schema_only_recovery%22
