### ISSUE TITLE
Logging settings

### ISSUE THREAD

**Issue by slnw** [Altinity/clickhouse-sink-connector#637]
Hi, I've set the env variable log level to error
```
> printenv | grep LOGG
LOGGING_LEVEL=ERROR
```
![Screenshot 2024-06-11 at 14 23 24](https://github.com/Altinity/clickhouse-sink-connector/assets/26124406/5d523d36-d58c-418f-be14-d4dcb6789d45)

but I still get the INFO log messages in the container stderr - 
![Screenshot 2024-06-11 at 14 23 07](https://github.com/Altinity/clickhouse-sink-connector/assets/26124406/2492992d-9346-4971-b08b-bd29cd3a43df)

**Comment by subkanthi** [comment]
Fixed in `2.2.0` , Please refer to [Logging](https://github.com/Altinity/clickhouse-sink-connector/blob/develop/doc/logging.md).
