### ISSUE TITLE
Error when parsing DDL for MySQL enum.

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#677]
Currently the MySQL DDL Parser looks for precision/scale for enum data type and displays an error message.

{"timeMillis":1720534716721,"thread":"main","level":"ERROR","loggerName":"com.altinity.clickhouse.debezium.embedded.ddl.parser.MySqlDDLParserListenerImpl","message":"Error parsing precision, scale : columnNamegender","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","contextMap":{},"threadId":1,"threadPriority":5}

**Comment by Selfeer** [comment]
with the build: `altinityinfra/clickhouse-sink-connector:693-f601ce52b00c74da98d4b6452019ad06d57eaac2-lt`

Before the fix:

```
clickhouse-sink-connector-lt-1  | 2024-07-19 10:57:49.323 ERROR - Error parsing precision, scale : columnNamestatus
clickhouse-sink-connector-lt-1  | 2024-07-19 10:57:49.323 INFO  - Executed Source DB DDL: CREATE TABLE example_table (
clickhouse-sink-connector-lt-1  |     id INT AUTO_INCREMENT PRIMARY KEY,
clickhouse-sink-connector-lt-1  |     status ENUM('pending', 'approved', 'rejected') NOT NULL
```

After the fix:

```
clickhouse-sink-connector-lt-1  | 2024-07-19 11:04:29.581 INFO  - Executed Source DB DDL: CREATE TABLE example_table2 (
clickhouse-sink-connector-lt-1  |     id INT AUTO_INCREMENT PRIMARY KEY,
clickhouse-sink-connector-lt-1  |     status ENUM('pending', 'approved', 'rejected') NOT NULL
clickhouse-sink-connector-lt-1  | ) Snapshot:false

```
