### ISSUE TITLE
We cant start grafana in sink connector, we have cert issue

### ISSUE THREAD

**Issue by minguyen9988** [Altinity/clickhouse-sink-connector#725]
```Error: ✗ Get "https://grafana.com/api/plugins/vertamedia-clickhouse-datasource/versions": tls: failed to verify certificate: x509: certificate signed by unknown authority```

We have this error when we try to run docker-compose in lightweight for grafana

**Comment by subkanthi** [comment]
Solution implemented copies the root certificate to the Docker container.
