### ISSUE TITLE
json validate error when parsing status

### ISSUE THREAD

**Issue by tellienne** [Altinity/clickhouse-sink-connector#734]
Hi guys!
We use a connector to transfer data from Postgres to Clickhouse.
We set up connector monitoring and try to parse the result from 
```
./sink-connector-client show_replica_status
```
by json exporter for prometheus, but parsing ends with an error

```
ts=2024-08-02T14:51:24.127Z caller=collector.go:129 level=error msg="Failed to unmarshal data to json" err="invalid character '-' after object key:value pair" data="[{\"Seconds_Behind_Source\":0},{\"Replica_Running\":true},{\"Database\":\"system\"},{\"record_insert_ts\":2024-08-02T14:51:22,\"offset_key\":\"[\\\"debezium-embedded-postgres\\\",{\\\"server\\\":\\\"embeddedconnector\\\"}]\",\"record_insert_seq\":12800,\"id\":\"d4f5d5c0-5e5c-4c06-9c01-d8a5f7316582\",\"offset_val\":\"{\\\"lsn_proc\\\":35252840718584,\\\"messageType\\\":\\\"INSERT\\\",\\\"lsn_commit\\\":35252840704528,\\\"lsn\\\":35252840718584,\\\"txId\\\":143351921,\\\"ts_usec\\\":1722610282065094}\"}]"

```
checking on https://jsonformatter.org/ also gives an error

```
Parse error on line 12:
...ord_insert_ts": 2024-08-02T15,    "offs
-----------------------^
Expecting 'EOF', '}', ',', ']', got 'undefined'
```

The status itself looks like this

```
[
  {
    "Seconds_Behind_Source": 0
  },
  {
    "Replica_Running": true
  },
  {
    "Database": "system"
  },
  {
    "record_insert_ts": 2024-08-02T15,
    "offset_key": "[\"debezium-embedded-postgres\",{\"server\":\"embeddedconnector\"}]",
    "record_insert_seq": 12993,
    "id": "a265900f-150f-452f-b726-12eec0dc181c",
    "offset_val": "{\"lsn_proc\":35253344986016,\"messageType\":\"INSERT\",\"lsn_commit\":35253344985968,\"lsn\":35253344986016,\"txId\":143359900,\"ts_usec\":1722611200377501}"
  }
]
```

**Comment by tellienne** [comment]
perhaps the connector already has an endpoint for collecting metrics in prometheus format?

**Comment by subkanthi** [comment]
yes it is, please use `metrics.enable: true` and `metrics.port: <port_number>`

**Comment by tellienne** [comment]
I see a lot of jvm metrics. This is useful, but we would also like to have metrics on the status data, like Replica_Running etc.

Is it possible to somehow parse json from show_replica_status correctly?

**Comment by subkanthi** [comment]
The `clickhouse_` and `clickhouse.` metrics have the lag metrics

```

**Comment by subkanthi** [comment]
public static final String CLICKHOUSE_SINK_RECORDS = "clickhouse.sink.records";

    public static final String CLICKHOUSE_SINK_BINLOG_POS = "clickhouse_sink_binlog_pos";

    public static final String CLICKHOUSE_SINK_GTID = "clickhouse_sink_gtid";

    public static final String CLICKHOUSE_SINK_PARTITION_OFFSET = "clickhouse_sink_partition_offset";

    public static final String CLICKHOUSE_DB_SINK_LAG = "clickhouse_sink_db_lag";

    public static final String CLICKHOUSE_DEBEZIUM_SINK_LAG = "clickhouse_sink_debezium_lag";

    public static final String CLICKHOUSE_NUM_RECORDS_BY_TOPIC = "clickhouse.sink.topics.num.records";

    public static final String CLICKHOUSE_SINK_DDL = "clickhouse.sink.ddl";

    public static final String CLICKHOUSE_NUM_ERROR_RECORDS_BY_TOPIC = "clickhouse.sink.topics.error.records";

    public static final String CLICKHOUSE_SINK_CONNECTOR_UPTIME = "clickhouse_sink_connector_uptime";

```

**Comment by subkanthi** [comment]
Added fix to change LocalDateTime to String
```
[
  {
    "Seconds_Behind_Source": 0
  },
  {
    "Replica_Running": true
  },
  {
    "Database": "system"
  },
  {
    "record_insert_ts": "2024-08-01T18:49:17",
    "offset_key": "[\"company-1\",{\"server\":\"embeddedconnector\"}]",
    "record_insert_seq": 1930,
    "id": "b36b89cb-eab2-49ef-a32f-84a56e251e75",
    "offset_val": "{\"ts_sec\":1722538005,\"file\":\"mysql-bin.000007\",\"pos\":342980483,\"gtids\":\"3b897da2-5043-11ef-899f-0242ac1e0002:1-9684745\"}"
  }
]
```
