### ISSUE TITLE
No macro 'cluster' in config while processing substitutions in '{cluster}' at '1' or macro is not supported here.

### ISSUE THREAD

**Issue by byte09** [Altinity/clickhouse-sink-connector#741]
Hello,
 
Sorry, can you tell me how to fix this problem:

{"log":"2024-08-07 11:03:38.348 INFO  - **** Task(0), AUTO CREATE TABLE (products) Database(metrika) *** \n","stream":"stdout","time":"2024-08-07T11:03:38.348941601Z"}
{"log":"2024-08-07 11:03:38.350 INFO  - **** AUTO CREATE TABLE for database(metrika), Query :CREATE TABLE metrika.`products` ON CLUSTER `{cluster}` (`product_id` Int64 NOT NULL,`name` String NOT NULL,`description` String NOT NULL,`_version` UInt64,`_sign` UInt8) Engine=ReplicatedReplacingMergeTree(_version, _sign) PRIMARY KEY(product_id) ORDER BY(product_id))\n","stream":"stdout","time":"2024-08-07T11:03:38.350985197Z"}
{"log":"2024-08-07 11:03:38.355 ERROR - **** Error creating table(products), database(metrika) ***\n","stream":"stdout","time":"2024-08-07T11:03:38.355638631Z"}
{"log":"java.sql.SQLException: Code: 139. DB::Exception: No macro 'cluster' in config while processing substitutions in '{cluster}' at '1' or macro is not supported here. (NO_ELEMENTS_IN_CONFIG) (version 23.8.8.20 (official build))\n","stream":"stdout","time":"2024-08-07T11:03:38.355653741Z"}

IN config :
- auto.create.tables: "true"

But i don't have clusters in ClickHouse, also non (standalone) server.

?

**Comment by subkanthi** [comment]
Hi @byte09 ,
do you have this defined in the configuration, this should be set to `false`
```
"auto.create.tables.replicated: "true"

```

**Comment by byte09** [comment]
Thanks, it's realy work!

**Comment by adamantal** [comment]
While turning off the creation of replicated tables solves the issue, for anyone who does want to replicate the table, a workaround could be to create the `cluster` macro that points to the ClickHouse cluster. E.g.:
```xml
<clickhouse>
  <macros>
    <cluster>default</cluster>
  </macros>
</clickhouse>
```
