### ISSUE TITLE
snapshot metrics

### ISSUE THREAD

**Issue by tellienne** [Altinity/clickhouse-sink-connector#744]
Hi!

We found in the Debezium documentation that Debezium can provide metrics about the launch of snapshots https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-monitoring

Is it possible to get these metrics from the connector?

**Comment by subkanthi** [comment]
Implemented in `altinityinfra/clickhouse-sink-connector:757-6df0a8da60cf54c5adc1d29f68f9b8e643fa02fb-lt`.

This fix only exposes the Debezium metrics to prometheus.
This can be tested by checking if the metrics show up on the prometheus UI.
