### ISSUE TITLE
sink-connector clickhouse_sink_connector_uptime metrics truncated

### ISSUE THREAD

**Issue by sarthaksingh-tomar** [Altinity/clickhouse-sink-connector#747]
Using sink-connector metrics in Prometheus/Grafana Dashboard.
<img width="1316" alt="Screenshot 2024-08-13 at 09 08 31" src="https://github.com/user-attachments/assets/fe0b9980-caaf-4fe7-a4c9-abf16fd80783">
Not sure why **clickhouse_sink_connector_uptime** metrics got truncated everyday even when sink-connector container is running fine.
```
CONTAINER ID   IMAGE                               COMMAND                  CREATED       STATUS       PORTS                                                                                                                    NAMES
3103ad56d05a   clickhouse-sink-connector-lt-2      "sh -c 'java -agentl…"   3 days ago    Up 3 days    0.0.0.0:7000->7000/tcp, :::7000->7000/tcp, 0.0.0.0:8083->8083/tcp, :::8083->8083/tcp                                   services-sink-connector-6-1
``` 
can you please take a look ?

**Comment by subkanthi** [comment]
Hi @sarthaksingh-tomar , the timer gets reset everytime the sink connector is restarted.
Can you check your configuration if you have
`restart.event.loop` set to `true`, its one reason the connector might restart 

![image](https://github.com/user-attachments/assets/41c4c902-9f89-4e50-8b28-f60875ebcb5e)

**Comment by sarthaksingh-tomar** [comment]
Thanks @subkanthi , it's working now 👍
