### ISSUE TITLE
CANNOT_GET_CREATE_TABLE_QUERY Exception - Table Not Created with auto.create.tables.replicated: "true"

### ISSUE THREAD

**Issue by Obey177** [Altinity/clickhouse-sink-connector#799]
We are using the ClickHouse Sink Connector v2.3.0-lt to transfer data from PostgreSQL to ClickHouse. When the configuration parameter auto.create.tables.replicated: "true" is set, tables are not created in ClickHouse. Instead, the following exception is logged:

> `clickhouse-sink-connector-lt-1  | 2024-09-09 08:38:40.517 INFO  - getTableEngineUsingShowTable exception
> clickhouse-sink-connector-lt-1  | java.sql.SQLException: Code: 390. DB::Exception: Table `Links` doesn't exist. (CANNOT_GET_CREATE_TABLE_QUERY) (version 24.7.3.42 (official build))
> clickhouse-sink-connector-lt-1  | , server ClickHouseNode [uri=http://192.168.0.2:8123/dev01db, options={custom_settings=allow_experimental_object_type=1,insert_allow_materialized_columns=1,client_name=Sink Connector Lightweight}]@-511221731
> clickhouse-sink-connector-lt-1  |       at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85) ~[app.jar:?]
> clickhouse-sink-connector-lt-1  |       at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31) ~[app.jar:?]
> clickhouse-sink-connector-lt-1  |       at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90) ~[app.jar:?]
> clickhouse-sink-connector-lt-1  |       at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:122) ~[app.jar:?]
> clickhouse-sink-connector-lt-1  |       at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474) ~[app.jar:?]
> clickhouse-sink-connector-lt-1  |       at com.altinity.clickhouse.sink.connector.db.DBMetadata.getTableEngineUsingShowTable(DBMetadata.java:111) [app.jar:?]
> clickhouse-sink-connector-lt-1  |       at com.altinity.clickhouse.sink.connector.db.DBMetadata.getTableEngine(DBMetadata.java:57) [app.jar:?]
> clickhouse-sink-connector-lt-1  |       at com.altinity.clickhouse.sink.connector.db.DbWriter.<init>(DbWriter.java:91) [app.jar:?]
> clickhouse-sink-connector-lt-1  |       at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.getDbWriterForTable(ClickHouseBatchRunnable.java:249) [app.jar:?]
> clickhouse-sink-connector-lt-1  |       at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:299) [app.jar:?]
> clickhouse-sink-connector-lt-1  |       at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:188) [app.jar:?]
> clickhouse-sink-connector-lt-1  |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
> clickhouse-sink-connector-lt-1  |       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
> clickhouse-sink-connector-lt-1  |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
> clickhouse-sink-connector-lt-1  |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
> clickhouse-sink-connector-lt-1  |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
> clickhouse-sink-connector-lt-1  |       at java.lang.Thread.run(Thread.java:833) [?:?]`

However, when the auto.create.tables.replicated: "true" line is commented out and we use only auto.create.tables: "true", the tables are created as expected in ClickHouse, but without replication support.

Connector version: 2.3.0-lt
PostgreSQL version: 14
ClickHouse version: 24.7.3.42
Docker Compose: 

> version: '3.4'
> 
> services:
>   clickhouse-sink-connector-lt:
>     image: altinity/clickhouse-sink-connector:2.3.0-lt
>     entrypoint: ["sh", "-c", "java -Xms4g -Xmx4g -jar /app.jar /config.yml com.altinity.clickhouse.debezium.embedded.ClickHouseDebeziumEmbeddedApplication"]
>     ports:
>       - "8083:8083"
>       - "5005:5005"
>       - "7000:7000"
>       - "39999:39999"
>     volumes:
>       - ./config.yml:/config.yml

Config:

> `name: "debezium-embedded-postgres"

> auto.create.tables.replicated: "true"

> database.hostname: "192.168.0.1"

> database.port: "5432"
> database.user: "user"
> database.password: "pass"
> database.server.name: "ER54"
> database.dbname: "mydb"
> schema.include.list: "linking"
> slot.name: "connector2"
> plugin.name: "pgoutput"
> table.include.list: "linking.\"Links\""
> clickhouse.server.url: "192.168.0.2"
> clickhouse.server.user: "user"
> clickhouse.server.password: "pass"
> clickhouse.server.port: "8123"
> database.allowPublicKeyRetrieval: "true"
> snapshot.mode: "initial"
> offset.flush.interval.ms: 5000
> connector.class: "io.debezium.connector.postgresql.PostgresConnector"
> offset.storage: "io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore"
> offset.storage.jdbc.offset.table.name: "altinity_sink_connector.replica_source_info"
> offset.storage.jdbc.url: "jdbc:clickhouse://192.168.0.2:8123/altinity_sink_connector"
> offset.storage.jdbc.user: "user"
> offset.storage.jdbc.password: "pass"
> offset.storage.jdbc.offset.table.ddl: "CREATE TABLE if not exists %s
> (
>     `id` String,
>     `offset_key` String,
>     `offset_val` String,
>     `record_insert_ts` DateTime,
>     `record_insert_seq` UInt64,
>     `_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
> )
> ENGINE = ReplacingMergeTree(_version)
> ORDER BY id
> SETTINGS index_granularity = 8192"
> offset.storage.jdbc.offset.table.delete: "delete from %s where 1=1"
> enable.snapshot.ddl: "true"
> auto.create.tables: "true"`

Please help, what should I do to make this setup work?

**Comment by tellienne** [comment]
we had the same problem when the clickhouse cluster was missing macros. maybe this issue  will help you https://github.com/Altinity/clickhouse-sink-connector/issues/676

**Comment by subkanthi** [comment]
@Obey177 please re-open if the solution proposed above did not help.
