### ISSUE TITLE
Single-threaded vs multi-threaded 

### ISSUE THREAD

**Issue by poweroftrue** [Altinity/clickhouse-sink-connector#836]
I'm using the single-threaded mode for a couple of Altinity Sink Connectors—lightweight ♥️—it's been working fine for a couple of days and has handled peak times pretty well.

When I tried multi-threaded mode, I ran into issues, especially when I tuned the queue size and other configs.

My question is: Do you guys see a big difference between multi-threaded and single-threaded modes in production environments?

I'm trying to gauge if the results are worth debugging the multi-threading problems I'm facing, like this one:

```
2024-09-17 21:07:37.986 ERROR - Invalid call to OffsetStorageWriter beginFlush() while already flushing, the framework should not allow this
```

I don't have resource constraints, if the multi-threaded mode will be 20% or faster, it's worth looking at it and giving it more resources to fly.

**Comment by poweroftrue** [comment]
Related: https://github.com/Altinity/clickhouse-sink-connector/issues/731

**Comment by aadant** [comment]
Maybe a recent debezium issue. Previous versions work fine with multiple threads. There is one thread that checkpoints the offset. @subkanthi do you have more info ?

**Comment by subkanthi** [comment]
> ```
> Invalid call to OffsetStorageWriter beginFlush() while already flushing, the framework should not allow this
> ```
Not sure if this is truly related to multiple threads, 
Debezium uses still some code from Kafka connect, will have to check with the Debezium Devs as they had plans to completely move away from the kafka connect code.

https://github.com/apache/kafka/blob/trunk/connect/runtime/src/main/java/org/apache/kafka/connect/storage/OffsetStorageWriter.java
https://groups.google.com/g/debezium/c/Rvl7nm3jte0

**Comment by poweroftrue** [comment]
Thanks @subkanthi @aadant!

If I lower the queue to 500 and batch to 100 and there are 5 threads or more the issue will appear, also, it first happened with a big queue and peak time where a lot of inserts happen, but, a faster way to reproduce it is to lower the queue size. I will take a deeper look at the cause check dbz issues.

But Is there a huge impact from having many threads? Will it make the replication much faster during peak inserts?

**Comment by subkanthi** [comment]
Hi @poweroftrue , Im working on getting some benchmark numbers to compare both modes, will get that published soon.

**Comment by poweroftrue** [comment]
Thanks @subkanthi
