### ISSUE TITLE
The 'snapshot.mode' value 'schema_only' is invalid PostgreSQL->ClickHouse

### ISSUE THREAD

**Issue by byte09** [Altinity/clickhouse-sink-connector#854]
Hi, can you help me?

I don't want to load the entire history by tables and use **snapshot.mode: "schema_only"** after start I get an error:

2024-10-02 04:18:55.675 ERROR - Error starting connectornull Message:Connector configuration is not valid. The 'snapshot.mode' value is invalid: Value must be one of always, never, initial_only, configuration_based, when_needed, initial, custom, no_data

Version: 2.2.1

My Settings:

name: "debezium-embedded-postgres"
database.hostname: "demo"
database.port: "5432"
database.user: "ghost"
database.password: "hhh"
database.server.name: "host"
database.dbname: "metr"

clickhouse.database.override.map:"metr:pap"

schema.include.list: metr
table.include.list: ""

slot.name:"dwh_clickhouse"
plugin.name:"pgoutput"
clickhouse.server.url: "sd"
clickhouse.server.user: "ddd"
clickhouse.server.password: "ddd"
clickhouse.server.port: "8123"
clickhouse.server.database: "pap"

snapshot.mode: "schema_only"
enable.snapshot.ddl: "false"
auto.create.tables: "false"

offset.flush.interval.ms: 5000
connector.class: "io.debezium.connector.postgresql.PostgresConnector"
auto.create.tables.replicated: "false"
skip_replica_start: "true"
ignore_delete: "true"
disable.ddl: "false"
disable.drop.truncate: "true"
schema.history.internal.schema.history.table.name:"pap.replicate_schema_history"
replacingmergetree.delete.column: "_sign"
buffer.max.records: "1000000"
thread.pool.size: 10
max.batch.size: 20000
max.queue.size: 100000

**Comment by subkanthi** [comment]
Please use `no_data` instead of `schema_only` , this was updated in the recent version of debezium.

**Comment by byte09** [comment]
I use no_data but have a error:

ERROR - Error starting connectorio.debezium.DebeziumException: The connector previously stopped while taking a snapshot, but now the connector is configured to never allow snapshots. Reconfigure the connector to use snapshots initially or when needed.

**Comment by subkanthi** [comment]
As the error says, unfortunately u have to use the `when_needed` as snapshot.mode or you can delete the offsets table and start again with `no_data`.
